import type { Question } from '../types';

/**
 * Challenge math questions for ninjas aged 10 to 12. Goal: stretch a
 * little further than the warm-up: multi-step word problems, fraction
 * and decimal operations, ratio and proportion, percentages, area,
 * averages, simple "find the missing number" algebra, powers, and a
 * pinch of probability and logic. Still real-life, still plain English,
 * just one or two more steps of thinking.
 *
 * Authoring rules (enforced by scripts/audit-questions.ts and the tests):
 *  - exactly 4 options, each non-empty and <= OPTION_MAX_CHARS
 *  - explanation <= EXPLANATION_MAX_CHARS (Telegram quiz-poll limit)
 *  - correctIndex is 0..3 and points at the right option
 *  - id starts with "challenge-" and is unique
 *  - the correct answer is spread across positions, not always first
 */
export const challengeQuestions: readonly Question[] = [
  {
    id: 'challenge-ratio-recipe',
    difficulty: 'challenge',
    topic: 'Ratio',
    scenario: 'A pancake recipe uses 2 cups of flour for every 3 cups of milk.',
    prompt: 'If you use 6 cups of flour, how many cups of milk do you need?',
    hint: 'Find how many times 2 fits into 6, then multiply 3 by that.',
    options: ['6 cups', '12 cups', '8 cups', '9 cups'],
    correctIndex: 3,
    explanation: '6 / 2 = 3 batches, so 3 x 3 = 9 cups of milk.',
  },
  {
    id: 'challenge-ratio-share',
    difficulty: 'challenge',
    topic: 'Ratio',
    scenario: 'Ahmed and his brother share 20 apples in the ratio 3 to 2.',
    prompt: 'How many apples does Ahmed get?',
    hint: 'Add the ratio parts (3 + 2 = 5) to find how many equal shares there are.',
    options: ['10 apples', '12 apples', '8 apples', '15 apples'],
    correctIndex: 1,
    explanation: '3 + 2 = 5 parts. Each part is 20 / 5 = 4, so Ahmed gets 3 x 4 = 12 apples.',
  },
  {
    id: 'challenge-percent-discount',
    difficulty: 'challenge',
    topic: 'Percentages',
    scenario: 'A shirt costs 200 pounds and the shop takes 25% off in a sale.',
    prompt: 'How much do you pay after the discount?',
    hint: 'First find 25% of 200 (that is one quarter), then take it off the price.',
    options: ['150 pounds', '160 pounds', '50 pounds', '140 pounds'],
    correctIndex: 0,
    explanation: '25% of 200 is 50. So you pay 200 - 50 = 150 pounds.',
  },
  {
    id: 'challenge-percent-of',
    difficulty: 'challenge',
    topic: 'Percentages',
    scenario: 'A class of 150 students is asked who walks to school, and 20% say yes.',
    prompt: 'How many students walk to school?',
    hint: '10% of 150 is 15. How many tens are in 20%?',
    options: ['30 students', '15 students', '45 students', '20 students'],
    correctIndex: 0,
    explanation: '10% of 150 is 15, so 20% is 15 x 2 = 30 students.',
  },
  {
    id: 'challenge-area-rect',
    difficulty: 'challenge',
    topic: 'Area',
    scenario: 'You are painting a rectangular wall and need to know its area.',
    prompt: 'The wall is 7 metres long and 4 metres tall. What is its area?',
    hint: 'Area of a rectangle is length times width. Do not add the sides.',
    options: ['22 sq m', '28 sq m', '11 sq m', '24 sq m'],
    correctIndex: 1,
    explanation: '7 x 4 = 28 square metres. (22 would be the perimeter.)',
  },
  {
    id: 'challenge-area-square',
    difficulty: 'challenge',
    topic: 'Area',
    scenario: 'A square rug sits in the middle of a room.',
    prompt: 'Each side of the rug is 9 metres. What is its area?',
    hint: 'Area of a square is one side multiplied by itself.',
    options: ['36 sq m', '72 sq m', '81 sq m', '18 sq m'],
    correctIndex: 2,
    explanation: '9 x 9 = 81 square metres. (36 would be the perimeter.)',
  },
  {
    id: 'challenge-average',
    difficulty: 'challenge',
    topic: 'Averages',
    scenario: 'Sara scored 8, 6, 10, and 8 in four short quizzes.',
    prompt: 'What is her average (mean) score?',
    hint: 'Add all four scores, then divide by how many quizzes there were.',
    options: ['7', '9', '8', '6'],
    correctIndex: 2,
    explanation: '8 + 6 + 10 + 8 = 32, and 32 / 4 = 8.',
  },
  {
    id: 'challenge-algebra-add',
    difficulty: 'challenge',
    topic: 'Find the Number',
    scenario: 'You think of a number, add 7 to it, and get 15.',
    prompt: 'What was the number you started with?',
    hint: 'Undo the "add 7" step by subtracting 7 from 15.',
    options: ['9', '7', '8', '22'],
    correctIndex: 2,
    explanation: '15 - 7 = 8, and you can check: 8 + 7 = 15.',
  },
  {
    id: 'challenge-algebra-multiply',
    difficulty: 'challenge',
    topic: 'Find the Number',
    scenario: 'A box of crayons is shared so that 4 equal groups make 36 crayons.',
    prompt: 'How many crayons are in each group?',
    hint: 'You are looking for the number that, times 4, gives 36.',
    options: ['6', '8', '9', '40'],
    correctIndex: 2,
    explanation: '36 / 4 = 9, and you can check: 4 x 9 = 36.',
  },
  {
    id: 'challenge-power-square',
    difficulty: 'challenge',
    topic: 'Powers',
    scenario: 'You are tiling a square floor that is 7 tiles along each side.',
    prompt: 'How many tiles do you need in total (that is 7 squared, or 7 to the power of 2)?',
    hint: '7 squared means 7 x 7.',
    options: ['14', '42', '49', '56'],
    correctIndex: 2,
    explanation: '7^2 = 7 x 7 = 49 tiles.',
  },
  {
    id: 'challenge-power-two',
    difficulty: 'challenge',
    topic: 'Powers',
    scenario: 'A piece of paper is folded in half again and again, doubling the layers each time.',
    prompt: 'After 5 folds the layers are 2 to the power of 5. What is 2 to the power of 5?',
    hint: 'Multiply 2 by itself 5 times: 2 x 2 x 2 x 2 x 2.',
    options: ['16', '64', '10', '32'],
    correctIndex: 3,
    explanation: '2 x 2 x 2 x 2 x 2 = 32 layers.',
  },
  {
    id: 'challenge-multistep-leftover',
    difficulty: 'challenge',
    topic: 'Word Problems',
    scenario: 'You have 50 pounds and buy a notebook for 12 pounds and a pen for 8 pounds.',
    prompt: 'How much money do you have left?',
    hint: 'First add up what you spent, then take it away from 50.',
    options: ['38 pounds', '30 pounds', '20 pounds', '32 pounds'],
    correctIndex: 1,
    explanation: '12 + 8 = 20 spent, and 50 - 20 = 30 pounds left.',
  },
  {
    id: 'challenge-multistep-change',
    difficulty: 'challenge',
    topic: 'Word Problems',
    scenario: 'You buy 3 toy cars that cost 45 pounds each and pay with a 200 pound note.',
    prompt: 'How much change do you get back?',
    hint: 'Work out the total cost first, then subtract it from 200.',
    options: ['55 pounds', '65 pounds', '75 pounds', '45 pounds'],
    correctIndex: 1,
    explanation: '3 x 45 = 135, and 200 - 135 = 65 pounds change.',
  },
  {
    id: 'challenge-fraction-add',
    difficulty: 'challenge',
    topic: 'Adding Fractions',
    scenario: 'You drink 1/4 of a bottle of water in the morning and 2/4 at lunch.',
    prompt: 'How much of the bottle have you drunk in total?',
    hint: 'The bottom numbers match, so just add the top numbers.',
    options: ['3/4', '3/8', '1/2', '4/8'],
    correctIndex: 0,
    explanation: '1/4 + 2/4 = 3/4 (add the tops, keep the bottom the same).',
  },
  {
    id: 'challenge-fraction-of-number',
    difficulty: 'challenge',
    topic: 'Fractions of Amounts',
    scenario: 'A bag holds 20 marbles and 3/4 of them are blue.',
    prompt: 'How many marbles are blue?',
    hint: 'Find 1/4 of 20 first, then take 3 of those quarters.',
    options: ['12', '16', '15', '10'],
    correctIndex: 2,
    explanation: '1/4 of 20 is 5, so 3/4 is 3 x 5 = 15 marbles.',
  },
  {
    id: 'challenge-decimal-multiply',
    difficulty: 'challenge',
    topic: 'Decimals',
    scenario: 'You buy 4 bottles of juice and each one holds 1.5 litres.',
    prompt: 'How many litres of juice is that in total?',
    hint: 'Multiply 1.5 by 4. Think of 1.5 as one and a half.',
    options: ['4.5 litres', '6 litres', '5.5 litres', '6.5 litres'],
    correctIndex: 1,
    explanation: '1.5 x 4 = 6 litres.',
  },
  {
    id: 'challenge-decimal-subtract',
    difficulty: 'challenge',
    topic: 'Decimals',
    scenario: 'You pay for a 3.75 pound snack with a 10 pound note.',
    prompt: 'How much change should you get?',
    hint: 'Subtract 3.75 from 10.00. Line up the decimal points.',
    options: ['6.25 pounds', '7.25 pounds', '6.75 pounds', '5.25 pounds'],
    correctIndex: 0,
    explanation: '10.00 - 3.75 = 6.25 pounds.',
  },
  {
    id: 'challenge-probability',
    difficulty: 'challenge',
    topic: 'Probability',
    scenario: 'A bag holds 3 red balls and 2 blue balls. You pull one out without looking.',
    prompt: 'What is the chance of picking a red ball?',
    hint: 'Probability is the number of red balls over the total number of balls.',
    options: ['2/5', '3/5', '3/2', '1/5'],
    correctIndex: 1,
    explanation: 'There are 3 red out of 5 balls in total, so the chance is 3/5.',
  },
  {
    id: 'challenge-speed-distance',
    difficulty: 'challenge',
    topic: 'Speed and Distance',
    scenario: 'A car drives at a steady 60 km per hour for 2 hours.',
    prompt: 'How far does the car travel?',
    hint: 'Distance is speed multiplied by time.',
    options: ['120 km', '30 km', '90 km', '180 km'],
    correctIndex: 0,
    explanation: '60 x 2 = 120 km.',
  },
  {
    id: 'challenge-speed-time',
    difficulty: 'challenge',
    topic: 'Speed and Distance',
    scenario: 'A train needs to cover 150 km and travels at 50 km per hour.',
    prompt: 'How many hours does the journey take?',
    hint: 'Time is distance divided by speed.',
    options: ['2 hours', '3 hours', '4 hours', '2 and a half hours'],
    correctIndex: 1,
    explanation: '150 / 50 = 3 hours.',
  },
  {
    id: 'challenge-multiply-stadium',
    difficulty: 'challenge',
    topic: 'Multiplication',
    scenario: 'A stadium has 5 stands, and each stand seats 1,200 people.',
    prompt: 'How many people can the stadium hold in total?',
    hint: 'Multiply the number of stands by the seats in one stand.',
    options: ['5,000', '600', '6,500', '6,000'],
    correctIndex: 3,
    explanation: '5 x 1,200 = 6,000 people.',
  },
  {
    id: 'challenge-percent-half',
    difficulty: 'challenge',
    topic: 'Percentages',
    scenario: 'A phone game has 86 levels and you have finished 50% of them.',
    prompt: 'How many levels have you finished?',
    hint: '50% means one half.',
    options: ['40', '46', '38', '43'],
    correctIndex: 3,
    explanation: '50% of 86 is 86 / 2 = 43 levels.',
  },
  {
    id: 'challenge-compare-fractions',
    difficulty: 'challenge',
    topic: 'Comparing Fractions',
    scenario: 'Two recipes use different fractions of a cup of sugar: 2/3 and 3/5.',
    prompt: 'Which fraction is larger, 2/3 or 3/5?',
    hint: 'Make the bottoms match. Use fifteenths: 2/3 = 10/15 and 3/5 = 9/15.',
    options: ['3/5', 'They are equal', '2/3', 'You cannot tell'],
    correctIndex: 2,
    explanation: '2/3 = 10/15 and 3/5 = 9/15, so 2/3 is larger.',
  },
  {
    id: 'challenge-ratio-eggs',
    difficulty: 'challenge',
    topic: 'Proportion',
    scenario: 'A cake for 4 people needs 8 eggs.',
    prompt: 'Using the same recipe, how many eggs do you need for 6 people?',
    hint: 'Find the eggs needed for 1 person first, then multiply by 6.',
    options: ['10 eggs', '16 eggs', '12 eggs', '14 eggs'],
    correctIndex: 2,
    explanation: '8 / 4 = 2 eggs per person, so 6 people need 2 x 6 = 12 eggs.',
  },
  {
    id: 'challenge-average-missing',
    difficulty: 'challenge',
    topic: 'Averages',
    scenario:
      'Omar scored 7 and 8 in his first two tests. He wants his average over three tests to be 8.',
    prompt: 'What does he need to score in the third test?',
    hint: 'Three tests with an average of 8 must add up to 3 x 8 = 24 in total.',
    options: ['8', '10', '9', '7'],
    correctIndex: 2,
    explanation: 'The three scores must total 24. 7 + 8 = 15, so he needs 24 - 15 = 9.',
  },
  {
    id: 'challenge-area-tiles',
    difficulty: 'challenge',
    topic: 'Area',
    scenario: 'A kitchen floor is covered with square tiles in a grid 5 tiles by 4 tiles.',
    prompt: 'How many tiles cover the floor?',
    hint: 'Multiply the number of tiles along one side by the number along the other.',
    options: ['18', '20', '9', '24'],
    correctIndex: 1,
    explanation: '5 x 4 = 20 tiles.',
  },
  {
    id: 'challenge-percent-tenoff',
    difficulty: 'challenge',
    topic: 'Percentages',
    scenario: 'A book costs 80 pounds and the shop gives 10% off.',
    prompt: 'What is the new price?',
    hint: '10% of 80 is 8. Take that off the original price.',
    options: ['70 pounds', '8 pounds', '72 pounds', '75 pounds'],
    correctIndex: 2,
    explanation: '10% of 80 is 8, so the new price is 80 - 8 = 72 pounds.',
  },
  {
    id: 'challenge-save-weeks',
    difficulty: 'challenge',
    topic: 'Word Problems',
    scenario: 'You save 15 pounds of your pocket money every week for 8 weeks.',
    prompt: 'How much will you have saved after 8 weeks?',
    hint: 'Multiply the weekly amount by the number of weeks.',
    options: ['115 pounds', '120 pounds', '105 pounds', '135 pounds'],
    correctIndex: 1,
    explanation: '15 x 8 = 120 pounds.',
  },
  {
    id: 'challenge-fraction-subtract',
    difficulty: 'challenge',
    topic: 'Subtracting Fractions',
    scenario: 'A jug is 5/6 full and you pour out 2/6 of the jug.',
    prompt: 'How much is left, in its simplest form?',
    hint: 'Subtract the tops (5 - 2), then see if the answer can be made simpler.',
    options: ['7/6', '1/2', '1/3', '1'],
    correctIndex: 1,
    explanation: '5/6 - 2/6 = 3/6, and 3/6 simplifies to 1/2.',
  },
  {
    id: 'challenge-square-pattern',
    difficulty: 'challenge',
    topic: 'Patterns',
    scenario: 'A pattern of dots makes squares: 1, 4, 9, 16, and keeps growing.',
    prompt: 'What is the next number in the pattern?',
    hint: 'These are square numbers: 1x1, 2x2, 3x3, 4x4. What comes next?',
    options: ['20', '21', '24', '25'],
    correctIndex: 3,
    explanation: 'They are squares, so the next is 5 x 5 = 25.',
  },
];
