import type { Question } from '../types';

/**
 * Warm-up math questions for ninjas aged 10 to 12. Goal: bread-and-
 * butter skills that build confidence: adding, subtracting, multiplying,
 * dividing, place value, simple fractions and decimals, money, time,
 * measurement, and easy geometry. Every scenario is a small real-life
 * story a kid would recognise.
 *
 * Authoring rules (enforced by scripts/audit-questions.ts and the tests):
 *  - exactly 4 options, each non-empty and <= OPTION_MAX_CHARS
 *  - explanation <= EXPLANATION_MAX_CHARS (Telegram quiz-poll limit)
 *  - correctIndex is 0..3 and points at the right option
 *  - id starts with "warmup-" and is unique
 *  - the correct answer is spread across positions, not always first
 */
export const warmupQuestions: readonly Question[] = [
  {
    id: 'warmup-add-snack',
    difficulty: 'warmup',
    topic: 'Addition',
    scenario: 'You stop at the school shop and buy a sandwich and a juice.',
    prompt: 'The sandwich costs 15 pounds and the juice costs 8 pounds. How much do you pay in total?',
    hint: 'Add the price of the sandwich to the price of the juice.',
    options: ['23 pounds', '22 pounds', '25 pounds', '20 pounds'],
    correctIndex: 0,
    explanation: '15 + 8 = 23 pounds.',
  },
  {
    id: 'warmup-subtract-change',
    difficulty: 'warmup',
    topic: 'Subtraction',
    scenario: 'Mom buys groceries and pays with a 300 pound note.',
    prompt: 'The bill is 237 pounds. How much change should she get back?',
    hint: 'Take the bill away from the money she handed over.',
    options: ['73 pounds', '63 pounds', '53 pounds', '37 pounds'],
    correctIndex: 1,
    explanation: '300 - 237 = 63 pounds.',
  },
  {
    id: 'warmup-add-savings',
    difficulty: 'warmup',
    topic: 'Addition',
    scenario: 'Karim is saving money in his piggy bank.',
    prompt: 'He already had 125 pounds and his uncle gives him 75 more. How much does he have now?',
    hint: 'Put the two amounts together.',
    options: ['190 pounds', '195 pounds', '200 pounds', '210 pounds'],
    correctIndex: 2,
    explanation: '125 + 75 = 200 pounds.',
  },
  {
    id: 'warmup-multiply-packs',
    difficulty: 'warmup',
    topic: 'Multiplication',
    scenario: 'A teacher hands out pencils for an art class.',
    prompt: 'There are 6 packs and each pack holds 8 pencils. How many pencils are there in total?',
    hint: 'Multiply the number of packs by the pencils in each pack.',
    options: ['42 pencils', '54 pencils', '40 pencils', '48 pencils'],
    correctIndex: 3,
    explanation: '6 x 8 = 48 pencils.',
  },
  {
    id: 'warmup-multiply-chairs',
    difficulty: 'warmup',
    topic: 'Multiplication',
    scenario: 'The school hall is being set up for a play.',
    prompt: 'The crew arranges 24 rows with 5 chairs in each row. How many chairs is that?',
    hint: 'Multiply the number of rows by the chairs in one row.',
    options: ['120 chairs', '110 chairs', '125 chairs', '100 chairs'],
    correctIndex: 0,
    explanation: '24 x 5 = 120 chairs.',
  },
  {
    id: 'warmup-divide-stickers',
    difficulty: 'warmup',
    topic: 'Division',
    scenario: 'You share a sheet of stickers equally with your friends.',
    prompt: 'There are 56 stickers and 8 friends. How many stickers does each friend get?',
    hint: 'Split the stickers into 8 equal groups.',
    options: ['6 stickers', '8 stickers', '7 stickers', '9 stickers'],
    correctIndex: 2,
    explanation: '56 / 8 = 7 stickers each.',
  },
  {
    id: 'warmup-divide-remainder',
    difficulty: 'warmup',
    topic: 'Division with Remainders',
    scenario: 'You put 30 sweets into small bags, 4 sweets in each bag.',
    prompt: 'After filling as many full bags as you can, how many sweets are left over?',
    hint: 'How many times does 4 fit into 30, and what is left behind?',
    options: ['1 sweet', '3 sweets', '0 sweets', '2 sweets'],
    correctIndex: 3,
    explanation: '4 x 7 = 28, and 30 - 28 = 2 sweets left over.',
  },
  {
    id: 'warmup-round-hundred',
    difficulty: 'warmup',
    topic: 'Rounding',
    scenario: 'A school reports how many books are in the library, rounded for a poster.',
    prompt: 'There are 487 books. What is 487 rounded to the nearest hundred?',
    hint: 'Look at the tens digit. Is it 5 or more, or less than 5?',
    options: ['500', '400', '480', '490'],
    correctIndex: 0,
    explanation: 'The tens digit is 8, so 487 rounds up to 500.',
  },
  {
    id: 'warmup-place-value',
    difficulty: 'warmup',
    topic: 'Place Value',
    scenario: 'A scoreboard shows the number 4,732.',
    prompt: 'What is the value of the digit 7 in 4,732?',
    hint: 'Which column is the 7 sitting in: ones, tens, hundreds, or thousands?',
    options: ['7', '70', '700', '7,000'],
    correctIndex: 2,
    explanation: 'The 7 is in the hundreds place, so its value is 700.',
  },
  {
    id: 'warmup-multiple-of-5',
    difficulty: 'warmup',
    topic: 'Multiples',
    scenario: 'A coach lines up players in groups of 5 for a drill.',
    prompt: 'Which of these numbers is a multiple of 5?',
    hint: 'Multiples of 5 always end in 0 or 5.',
    options: ['32', '53', '45', '24'],
    correctIndex: 2,
    explanation: '45 ends in 5, so it is a multiple of 5 (5 x 9 = 45).',
  },
  {
    id: 'warmup-not-a-factor',
    difficulty: 'warmup',
    topic: 'Factors',
    scenario: 'You want to split 12 cupcakes into equal rows with none left over.',
    prompt: 'Which of these numbers is NOT a factor of 12?',
    hint: 'A factor divides 12 exactly, with nothing left over.',
    options: ['3', '4', '5', '6'],
    correctIndex: 2,
    explanation: '12 / 5 = 2 remainder 2, so 5 does not divide 12 exactly. 3, 4, and 6 do.',
  },
  {
    id: 'warmup-half-of',
    difficulty: 'warmup',
    topic: 'Fractions',
    scenario: 'You and your sister share a box of 18 dates equally.',
    prompt: 'What is half of 18?',
    hint: 'Halving means splitting into two equal parts.',
    options: ['8', '9', '10', '6'],
    correctIndex: 1,
    explanation: '18 / 2 = 9 dates each.',
  },
  {
    id: 'warmup-compare-fractions',
    difficulty: 'warmup',
    topic: 'Comparing Fractions',
    scenario: 'Two friends each eat part of an identical chocolate bar.',
    prompt: 'Which is the bigger share, 1/2 or 1/3?',
    hint: 'With the same whole, fewer equal parts means each part is bigger.',
    options: ['They are equal', '1/2', '1/3', 'You cannot tell'],
    correctIndex: 1,
    explanation: 'Splitting into 2 gives bigger pieces than splitting into 3, so 1/2 is bigger.',
  },
  {
    id: 'warmup-fraction-pizza',
    difficulty: 'warmup',
    topic: 'Fractions',
    scenario: 'A pizza is cut into 8 equal slices and you eat 3 of them.',
    prompt: 'What fraction of the pizza is left?',
    hint: 'Start from 8/8 (the whole) and take away the slices you ate.',
    options: ['3/8', '5/8', '8/5', '5/3'],
    correctIndex: 1,
    explanation: '8 - 3 = 5 slices left out of 8, which is 5/8.',
  },
  {
    id: 'warmup-add-decimals-money',
    difficulty: 'warmup',
    topic: 'Decimals',
    scenario: 'At the bakery you buy a roll for 2.50 and a cookie for 1.75.',
    prompt: 'How much do you spend in total?',
    hint: 'Line up the decimal points, then add.',
    options: ['4.20', '3.25', '4.25', '4.15'],
    correctIndex: 2,
    explanation: '2.50 + 1.75 = 4.25.',
  },
  {
    id: 'warmup-compare-decimals',
    difficulty: 'warmup',
    topic: 'Decimals',
    scenario: 'Two runners record their times, and you compare two distances in metres.',
    prompt: 'Which number is larger, 0.7 or 0.65?',
    hint: 'Think of 0.7 as 0.70, then compare like normal numbers.',
    options: ['0.7', '0.65', 'They are equal', 'You cannot compare them'],
    correctIndex: 0,
    explanation: '0.7 is the same as 0.70, and 0.70 is bigger than 0.65.',
  },
  {
    id: 'warmup-time-movie',
    difficulty: 'warmup',
    topic: 'Time',
    scenario: 'A film starts at 4:15 in the afternoon and ends at 6:00.',
    prompt: 'How long is the film?',
    hint: 'Count from 4:15 to 6:00 in steps you find easy.',
    options: ['2 h 15 min', '1 h 45 min', '1 h 15 min', '1 h 30 min'],
    correctIndex: 1,
    explanation: '4:15 to 6:15 would be 2 hours, but it ends at 6:00, so it is 1 h 45 min.',
  },
  {
    id: 'warmup-time-add',
    difficulty: 'warmup',
    topic: 'Time',
    scenario: 'You spend 40 minutes on homework and then 35 minutes reading.',
    prompt: 'How much time is that altogether?',
    hint: 'Add the minutes, then swap 60 minutes for 1 hour.',
    options: ['1 h 5 min', '1 h 25 min', '1 h 15 min', '75 min exactly an hour'],
    correctIndex: 2,
    explanation: '40 + 35 = 75 minutes, which is 1 hour and 15 minutes.',
  },
  {
    id: 'warmup-cm-to-m',
    difficulty: 'warmup',
    topic: 'Measurement',
    scenario: 'You measure the length of your bed with a tape measure.',
    prompt: 'The bed is 250 cm long. How many metres is that?',
    hint: 'There are 100 cm in 1 metre.',
    options: ['25 m', '0.25 m', '250 m', '2.5 m'],
    correctIndex: 3,
    explanation: '250 / 100 = 2.5 metres.',
  },
  {
    id: 'warmup-kg-to-g',
    difficulty: 'warmup',
    topic: 'Measurement',
    scenario: 'A bag of rice is labelled in kilograms at the shop.',
    prompt: 'The bag weighs 3 kg. How many grams is that?',
    hint: 'There are 1000 grams in 1 kilogram.',
    options: ['300 g', '3,000 g', '30 g', '30,000 g'],
    correctIndex: 1,
    explanation: '3 x 1000 = 3,000 grams.',
  },
  {
    id: 'warmup-perimeter-square',
    difficulty: 'warmup',
    topic: 'Perimeter',
    scenario: 'You build a square pen for a rabbit with equal sides.',
    prompt: 'Each side is 6 metres long. What is the perimeter (the distance all the way around)?',
    hint: 'A square has 4 equal sides. Add them all, or multiply one side by 4.',
    options: ['36 m', '12 m', '24 m', '18 m'],
    correctIndex: 2,
    explanation: '4 x 6 = 24 metres around. (36 would be the area, not the perimeter.)',
  },
  {
    id: 'warmup-perimeter-rect',
    difficulty: 'warmup',
    topic: 'Perimeter',
    scenario: 'A garden bed is shaped like a rectangle.',
    prompt: 'It is 8 metres long and 3 metres wide. What is the perimeter?',
    hint: 'Add all four sides: two lengths and two widths.',
    options: ['11 m', '24 m', '16 m', '22 m'],
    correctIndex: 3,
    explanation: '8 + 3 + 8 + 3 = 22 metres.',
  },
  {
    id: 'warmup-multiply-notebooks',
    difficulty: 'warmup',
    topic: 'Money',
    scenario: 'You buy notebooks for the new school year.',
    prompt: 'Each notebook costs 12 pounds and you buy 3 of them. How much do you pay?',
    hint: 'Multiply the price of one notebook by how many you buy.',
    options: ['33 pounds', '36 pounds', '39 pounds', '24 pounds'],
    correctIndex: 1,
    explanation: '12 x 3 = 36 pounds.',
  },
  {
    id: 'warmup-add-passengers',
    difficulty: 'warmup',
    topic: 'Addition',
    scenario: 'A bus picks up people at two stops.',
    prompt: 'There were 28 passengers, then 19 more got on. How many are on the bus now?',
    hint: 'Add the people already on the bus to the new ones.',
    options: ['37', '47', '46', '57'],
    correctIndex: 1,
    explanation: '28 + 19 = 47 passengers.',
  },
  {
    id: 'warmup-pattern-threes',
    difficulty: 'warmup',
    topic: 'Patterns',
    scenario: 'A number pattern goes 3, 6, 9, 12, and keeps going.',
    prompt: 'What is the next number in the pattern?',
    hint: 'Look at the jump from one number to the next.',
    options: ['14', '15', '16', '18'],
    correctIndex: 1,
    explanation: 'Each step adds 3, so after 12 comes 15.',
  },
  {
    id: 'warmup-pattern-double',
    difficulty: 'warmup',
    topic: 'Patterns',
    scenario: 'A number pattern goes 2, 4, 8, 16, and keeps going.',
    prompt: 'What is the next number in the pattern?',
    hint: 'Each number is made from the one before it. What are you doing to it?',
    options: ['18', '20', '24', '32'],
    correctIndex: 3,
    explanation: 'Each number doubles, so after 16 comes 32.',
  },
  {
    id: 'warmup-compare-thousands',
    difficulty: 'warmup',
    topic: 'Comparing Numbers',
    scenario: 'Four classes report how many steps they walked in a charity day.',
    prompt: 'Which of these is the greatest number?',
    hint: 'Compare the digits from the left: thousands first, then hundreds.',
    options: ['1,209', '1,290', '1,029', '1,092'],
    correctIndex: 1,
    explanation: 'All start with 1 thousand. 1,290 has the most hundreds (2) and the biggest tens, so it wins.',
  },
  {
    id: 'warmup-divide-share-money',
    difficulty: 'warmup',
    topic: 'Division',
    scenario: 'Five cousins share a 60 pound gift equally.',
    prompt: 'How much money does each cousin get?',
    hint: 'Split 60 into 5 equal parts.',
    options: ['10 pounds', '15 pounds', '12 pounds', '11 pounds'],
    correctIndex: 2,
    explanation: '60 / 5 = 12 pounds each.',
  },
  {
    id: 'warmup-double-number',
    difficulty: 'warmup',
    topic: 'Doubling',
    scenario: 'A recipe makes 47 cookies, and you decide to make double for a party.',
    prompt: 'What is double 47?',
    hint: 'Double means add the number to itself.',
    options: ['84', '94', '96', '88'],
    correctIndex: 1,
    explanation: '47 + 47 = 94 cookies.',
  },
  {
    id: 'warmup-half-larger',
    difficulty: 'warmup',
    topic: 'Halving',
    scenario: 'A 250 page book is read by two friends who split it in half.',
    prompt: 'How many pages is half of 250?',
    hint: 'Halve the hundreds and the rest, then add.',
    options: ['120', '130', '115', '125'],
    correctIndex: 3,
    explanation: '250 / 2 = 125 pages.',
  },
];
